// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  navigation: dynamic(() => import("./Navigation")),
  project: dynamic(() => import("./Project")),
  small_background_image: dynamic(() => import("./SmallBackgroundImage")),
};
